services:
  wine_container:
    image: zwhy2025/wine-docker:base
    container_name: wine_container
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./wine-home:/home/wechat
    privileged: true
    restart: unless-stopped
